# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gear_sync
spring.datasource.username=postgres
spring.datasource.password=Dita8220#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.datasource.platform=postgresql
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true

# H2 console (optional)
spring.h2.console.enabled=true

# Server port
server.port=8090